swipe:
  3:
    left:
      command: 'xdotool key alt+Left'
    right:
      command: 'xdotool key alt+Right'
    # up:
    #   command: 'xdotool key ctrl+t'
    #   threshold: 1.5
    # down:
    #   command: 'xdotool key ctrl+w'
    #   threshold: 1.5
  4:
    left:
      command: 'xdotool key ctrl+alt+Left'
    right:
      command: 'xdotool key ctrl+alt+Right'
    up:
      command: 'xdotool key ctrl+alt+Up'
    down:
      command: 'xdotool key ctrl+alt+Down'

threshold:
  swipe: 1.5

interval:
  swipe: 1
